" Globally use smaller tabs
set tabstop=2
" if we wanted to do it for a filetype, we could do
" autocmd Filetype css setlocal tabstop=4

" Solarized Light
set background=dark
colorscheme solarized8

" Use system clipboard
set clipboard=unnamed

" Line endings?
set ff=unix

" Line numbers
set nu

" Moar colourzzzz
set termguicolors

syntax on
autocmd Filetype gitcommit setlocal spell textwidth=72

syntax enable
set ruler
set rulerformat=%55(%{strftime('%a\ %b\ %e\ %I:%M\ %p')}\ %5l,%-6(%c%V%)\ %P%)
let timer = timer_start(4000, 'UpdateStatusBar',{'repeat':-1})
function! UpdateStatusBar(timer)
  execute 'let &ro = &ro'
endfunction

" show whitespace
set listchars=tab:>-,trail:~,extends:>,precedes:<
set list
