buf = github.com/bufbuild/buf/cmd/buf
dlv = github.com/go-delve/delve/cmd/dlv
goimports = golang.org/x/tools/cmd/goimports
gomodifytags = github.com/fatih/gomodifytags
goplay = github.com/haya14busa/goplay/cmd/goplay
gopls = golang.org/x/tools/gopls
gotests = github.com/cweill/gotests/gotests
gow = github.com/mitranim/gow
grpcurl = github.com/fullstorydev/grpcurl/cmd/grpcurl
gup = github.com/nao1215/gup
impl = github.com/josharian/impl
jy = github.com/sourcegraph/jy
mockgen = go.uber.org/mock/mockgen
pact-go = github.com/pact-foundation/pact-go/v2
protoc-gen-connect-go = connectrpc.com/connect/cmd/protoc-gen-connect-go
protoc-gen-doc = github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc
protoc-gen-go = google.golang.org/protobuf/cmd/protoc-gen-go
staticcheck = honnef.co/go/tools/cmd/staticcheck
yj = github.com/sourcegraph/yj
