# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Load zgen for fast zsh plugins
. "${HOME}/.zsh/zsh.d/zgen.zsh"

# Load fzf for fancier searching
. "${HOME}/.zsh/zsh.d/fzf.zsh"

# Potential Darwin addons
. "${HOME}/.zsh/zsh.d/darwin.zsh"

# CDPATH instead of aliases to different paths
export CDPATH="${CDPATH}:${HOME}/src2:${HOME}/src:${HOME}/work:${HOME}/src/go/src"

if [ -f "${HOME}/.zshrc-extras" ]; then
  . "${HOME}/.zshrc-extras"
else
  echo "Missing zshrc-extras from private-dotfiles"
fi

export PATH="/usr/local/go/bin:${HOME}/.yarn/bin:${HOME}/.config/yarn/global/node_modules/.bin:${PATH}"

export DOCKER_BUILDKIT=1
export KUSTOMIZE_ENABLE_ALPHA_COMMANDS=true

### History
setopt extended_history hist_no_store hist_ignore_dups hist_expire_dups_first hist_find_no_dups inc_append_history share_history hist_reduce_blanks hist_ignore_space
export HISTFILE=~/.zsh_history
export HISTSIZE=1000000
export SAVEHIST=1000000


### Some..  options
setopt autocd beep extendedglob nomatch rc_quotes
unsetopt notify

if [[ "$(uname)" == "Darwin" ]]; then
  . "$(brew --prefix asdf)/asdf.sh"
fi

export PATH="${HOME}/.mix/escripts:/usr/local/opt/ruby/bin:${PATH}"

if type rg &> /dev/null; then
    export FZF_DEFAULT_COMMAND='rg --files --hidden'
fi

export BAT_THEME="Solarized (light)"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"
export JAVA_HOME=/opt/homebrew/Cellar/openjdk/17.0.2/libexec/openjdk.jdk/Contents/Home
export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"
export PATH="/opt/homebrew/opt/node@16/bin:$PATH"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Created by `pipx` on 2022-04-28 16:07:08
export PATH="$PATH:$HOME/.local/bin"
export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
export PATH="/opt/homebrew/lib/ruby/gems/3.1.0/bin:$PATH"
export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"

[ -f /opt/homebrew/etc/profile.d/autojump.sh ] && . /opt/homebrew/etc/profile.d/autojump.sh

# added by Nix installer
if [ -e $HOME/.nix-profile/etc/profile.d/nix.sh ]; then
  . $HOME/.nix-profile/etc/profile.d/nix.sh;
fi

export NIX_PATH=$HOME/.nix-defexpr/channels:/nix/var/nix/profiles/per-user/root/channels${NIX_PATH:+:$NIX_PATH}
